
#### FIG ENV VARIABLES ####
# Please make sure this block is at the start of this file.
[ -s ~/.fig/shell/pre.sh ] && source ~/.fig/shell/pre.sh
#### END FIG ENV VARIABLES ####
# This launches Tmux automatically
#if [ "$TMUX" = "" ]; then tmux -2; fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CONFIG=$HOME/.zsh
ZSH_THEME="gentoo"
COMPLETION_WAITING_DOTS="true"
ZSH_DISABLE_COMPFIX=true

plugins=(brew bundler colorize rbenv gem git github macos rails ruby extract tmux tmuxinator vagrant docker)
fpath=(/usr/local/share/zsh-completions $fpath)
fpath=(~/.zsh/completion $fpath)

## Completions from Homebrew
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  autoload -Uz compinit
  compinit
fi

### PURE PROMPT
#fpath+=$HOME/.zsh/pure
#autoload -U promptinit; promptinit
#
### PURE OPTIONS
## turn on git stash status
#zstyle :prompt:pure:git:stash show yes
#
#prompt pure


source $ZSH/oh-my-zsh.sh
source $ZSH_CONFIG/*.zsh

# Customize to your needs...
export PATH=/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/X11/bin:/usr/local:/usr/local/opt/e2fsprogs/bin:./node_modules/.bin:/usr/local/share/npm/bin:/usr/local/opt/go/libexec/bin:/usr/local/opt/go/libexec/bin

#export LDFLAGS="-L/usr/local/opt/curl/lib"
#export CPPFLAGS="-I/usr/local/opt/curl/include"
#export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

#export HOMEBREW_FORCE_BREWED_CURL=1
export EDITOR='vim'
export NODE_PATH="/usr/local/lib/node"
export GOPATH="$HOME/Code/_misc/golang"
export FZF_CTRL_R_OPTS='--sort'
export SSH_AUTH_SOCK=~/.1password/agent.sock

#export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

unsetopt correct_all
#BUNDLED_COMMANDS="ruby rails"

# Fix Home/End keys
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line

[[ -s "$HOME/.tmuxifier/init.sh" ]] && source "$HOME/.tmuxifier/init.sh"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  autoload -Uz compinit
  compinit
fi

eval "$(starship init zsh)"

source ~/.zsh/iterm2_shell_integration.zsh
#### FIG ENV VARIABLES ####
# Please make sure this block is at the end of this file.
[ -s ~/.fig/fig.sh ] && source ~/.fig/fig.sh
#### END FIG ENV VARIABLES ####
