{ config, pkgs, lib, ... }:

{
  # Deploy ZSH configuration from repository
  # Your config is version controlled in config/zsh/

  programs.zsh = {
    enable = true;
    enableCompletion = true;

    # Put .zshrc in ~/.config/zsh/ instead of ~/
    dotDir = ".config/zsh";

    # History file location (XDG compliant)
    history = {
      path = "${config.xdg.stateHome}/zsh/zsh_history";
      size = 50000;
      save = 50000;
    };

    # ZSH plugins
    plugins = [
      {
        name = "zsh-completions";
        src = pkgs.zsh-completions;
        file = "share/zsh-completions/zsh-completions.plugin.zsh";
      }
      {
        name = "zsh-autosuggestions";
        src = pkgs.zsh-autosuggestions;
        file = "share/zsh-autosuggestions/zsh-autosuggestions.zsh";
      }
      {
        name = "zsh-syntax-highlighting";
        src = pkgs.zsh-syntax-highlighting;
        file = "share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh";
      }
    ];

    # Load custom zshrc after home-manager initialization
    initContent = ''
      # Source custom ZSH configuration
      if [[ -f "${config.xdg.configHome}/zsh/zshrc" ]]; then
        source "${config.xdg.configHome}/zsh/zshrc"
      fi
    '';
  };

  # Deploy your ZSH configuration files (excluding .zshrc which is generated by home-manager)
  xdg.configFile."zsh/zshrc" = {
    source = ../../../config/zsh/zshrc;
  };

  xdg.configFile."zsh/aliases" = lib.mkIf
    (builtins.pathExists ../../../config/zsh/aliases) {
    source = ../../../config/zsh/aliases;
    recursive = true;
  };

  xdg.configFile."zsh/functions" = lib.mkIf
    (builtins.pathExists ../../../config/zsh/functions) {
    source = ../../../config/zsh/functions;
    recursive = true;
  };
}