# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CONFIG=$HOME/.zsh
ZSH_THEME="gentoo"
COMPLETION_WAITING_DOTS="true"
plugins=(brew bundler colorized-man capistrano colorize rbenv mosh tmux ssh-agent sublime pow powder forklift cp postgres gem git git-flow github npm osx pow rails ruby extract tmux tmuxinator)

source $ZSH/oh-my-zsh.sh
source $ZSH_CONFIG/*.sh


# Customize to your needs...
export PATH=/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/X11/bin:/usr/local:./node_modules/.bin:/usr/local/share/npm/bin:/usr/local/opt/go/libexec/bin:/usr/local/opt/go/libexec/bin

# =================== #
#  Personal Settings  #
# =================== #
unsetopt correct_all

alias m='mvim'
alias v='vim'
alias weechat='weechat-curses'
alias twitter='ttytter'
alias adn='texapp'
alias t='tmux -2'
alias zr='source ~/.zshrc'

#BUNDLED_COMMANDS="ruby rails"

export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export TERM='screen-256color'
export EDITOR='vim'
export NODE_PATH="/usr/local/lib/node"
export CURL_CA_BUNDLE='/usr/local/certs/cacert.pem'
export GOPATH="$HOME/.go"

[[ -s "$HOME/.tmuxifier/init.sh" ]] && source "$HOME/.tmuxifier/init.sh"
