# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_CONFIG=$HOME/.zsh
ZSH_THEME="amuse"
COMPLETION_WAITING_DOTS="true"
plugins=(brew bundler colorized-man capistrano colorize rbenv  mosh tmux ssh-agent sublime pow powder forklift cp postgres gem git git-flow github npm osx pow rails ruby extract tmux tmuxinator vagrant chef)

source $ZSH/oh-my-zsh.sh
source $ZSH_CONFIG/*.sh


# Customize to your needs...
export PATH=$PATH:/usr/local/bin:/bin:/usr/sbin:/sbin:/usr/bin:/usr/X11/bin:/usr/local:./node_modules/.bin:/usr/local/share/npm/bin:/usr/local/opt/go/libexec/bin:/usr/local/opt/go/libexec/bin

# =================== #
#  Personal Settings  #
# =================== #
unsetopt correct_all

alias m='mvim'
alias v='vim'
#alias weechat='weechat-curses'
alias twitter='ttytter'
alias adn='texapp'
alias t='tmux -2'
alias zr='source ~/.zshrc'
alias python='python3'
alias pip='pip3'

#BUNDLED_COMMANDS="ruby rails"

#export TERM='screen-256color'
export EDITOR='vim'
export NODE_PATH="/usr/local/lib/node"
export GOPATH="$HOME/.go"

[[ -s "$HOME/.tmuxifier/init.sh" ]] && source "$HOME/.tmuxifier/init.sh"
source ~/.fzf.zsh # https://github.com/junegunn/fzf

#echo 'eval "$(chef shell-init zsh)"' # ChefDK
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
